version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "13:00"
      timezone: "Asia/Kolkata"
  
  labels: 
    - "dependencies update"
  
  target-branch: "main"
